# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6f19d7f19b9d25d50a6135b4a3f974fa11a6b687edf7039a05e232dd17f03527c73f308d95770987ad9602f6aba2d7ea1b2e3c1bdd88cd9e61ff0a6789ca40b

test:
  secret_key_base: ff563257f4b701759d0ba904db71579bd93eba539c74ca1f0948e42b3304b089015b166188116e3583b24aa984aafed2977cc96675d2bab9d381b171168575f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
